Repository PratikMane0112/TelMedSphere, pull requests merged in 2025-02, with the labels that each got.

#216 feat: added content and styling changes to aboutus page
  frontend/public/aboutus-image.png
  frontend/src/index.css
  frontend/src/pages/AboutUs.jsx
Labels: 🚨 change suggested

#217 feat: added complete feedback system
  backend/app.py
  frontend/src/components/landingPage/TestimonialCarousel.jsx
  frontend/src/pages/Feedback.jsx
  frontend/src/pages/LandingPage.jsx
Labels: 🚨 change suggested

#222 added cursor trail
  frontend/src/App.jsx
  frontend/src/components/common/Cursortrail.jsx
Labels: 🕓 under review, 🚨 change suggested

#232 Update Firebase Authentication Setup: Move Config to .env, Modify .gitignore, Update .env.example, Update EnvVarSetUpGuideline.md, and Add Backend Dependencies
  .github/EnvVarSetUpGuideline.md
  backend/.env.example
  backend/requirements.txt
  frontend/.env.example
  frontend/.gitignore
  frontend/src/firebase.js
Labels: SWOC, Advance

#236 added license section
  README.md
Labels: 🚨 change suggested

#238 create privacy policy page with attractive and responsive UI (Closes #237)
  frontend/src/App.jsx
  frontend/src/data/footerData.jsx
  frontend/src/pages/Privacy.jsx
  frontend/src/routes/RouterRoutes.jsx
Labels: 🚨 change suggested

#243 🚀 Enhanced Contact Page with Hover Effects 📝
  frontend/src/components/form/Accountform.jsx
  frontend/src/pages/ContactUs.jsx
Labels: 🚨 change suggested, ☎️ on hold

#272 Fixed Rating Bug & Enhanced Doctor Availability Indication
  backend/app.py
  frontend/src/pages/Home.jsx
Labels: ☎️ on hold

#270 Updated the design of Heading on Home page (Added the typing effect)
  frontend/src/pages/LandingPage.jsx
  frontend/tailwind.config.js
Labels: 🚨 change suggested

#293 Enhance Frontend Logic for Feedback Submission and Public Visibility
  backend/app.py
  frontend/src/components/landingPage/TestimonialCarousel.jsx
  frontend/src/pages/Feedback.jsx
Labels: 🚨 change suggested

#309 fix: footer bugs resolved
  frontend/src/components/common/Footer.jsx
Labels: SWOC, Advance

#329 Added dark theme for AccountForm.jsx
  frontend/src/components/form/Accountform.jsx
Labels: SWOC, Beginner

#365 Added dark theme for MedicineDetails.jsx and MedicineSummary.jsx
  frontend/src/components/medicines/MedicineSummary.jsx
  frontend/src/pages/MedicineDetails.jsx
  frontend/tailwind.config.js
Labels: SWOC, Intermediate

#354 Added dark theme for DataGrid and Insufficient Balance Modal inside Doctors.jsx
  frontend/colors.js
  frontend/src/components/common/Footer.jsx
  frontend/src/components/common/Header.jsx
  frontend/src/pages/Doctors.jsx
  frontend/src/pages/Home.jsx
  frontend/src/pages/LandingPage.jsx
Labels: SWOC, Advance

#362 Added dark theme for Medicines.jsx, FeaturedProducts.jsx, TopProducts.jsx, and ProductCard.jsx
  frontend/src/components/medicines/FeaturedProducts.jsx
  frontend/src/components/medicines/ProductCard.jsx
  frontend/src/components/medicines/TopProducts.jsx
  frontend/src/pages/Medicines.jsx
Labels: SWOC, Advance

#371 Added dark theme for MedicineDetails.jsx and EmptyView.jsx (Cart)
  frontend/src/components/cart/EmptyView.jsx
  frontend/src/pages/Cart.jsx
Labels: SWOC, Beginner

#380 fix: Duplicate backgroundColor keys in the Doctors.jsx file
  frontend/src/pages/Doctors.jsx
Labels: SWOC, Beginner

#382 Added dark theme for ErrorPage.jsx
  frontend/src/pages/ErrorPage.jsx
Labels: SWOC, Intermediate

#378 fix: added responsiveness in mobile ui
  frontend/src/components/medicines/ProductCard.jsx
  frontend/src/pages/MedicineDetails.jsx
Labels: 🚨 change suggested

#390 Fix Wallet Transaction Issues After Meeting
  backend/app.py
  frontend/src/pages/Home.jsx
  frontend/src/pages/MeetPage.jsx
Labels: SWOC, Intermediate
