Repository PratikMane0112/TelMedSphere, pull requests merged in 2025-01, with the labels that each got.

#50 new-phone-validation
  frontend/src/components/form/Accountform.jsx
Labels: 🥳 completed, 🐥 medium, KWOC

#56 Feature/add tailwind: Add PostCSS Configuration for Tailwind CSS
  backend/.env.example
  frontend/.env.example
  frontend/package-lock.json
  frontend/package.json
  frontend/postcss.config.js
  frontend/src/App.jsx
  frontend/src/styles/style.scss
  frontend/tailwind.config.js
Labels: KWOC

#91 Converted SCSS Styling to Tailwind in EmptyView.jsx and cart.jsx Main Container
  frontend/colors.js
  frontend/src/components/cart/CartItem.jsx
  frontend/src/components/cart/EmptyView.jsx
  frontend/src/pages/Cart.jsx
  frontend/src/styles/components/_emptyview.scss
  frontend/src/styles/style.scss
Labels: 🚨 change suggested

#95 Converted SCSS Styling to Tailwind in CartItem.jsx
  frontend/src/components/cart/CartItem.jsx
  frontend/src/pages/Cart.jsx
Labels: SWOC, Beginner

#111 Addition of a register button next to the login button on the header.
  frontend/src/components/common/Header.jsx
  frontend/src/components/form/Accountform.jsx
  frontend/src/styles/components/_header.scss
Labels: SWOC, Advance

#114 Update EnvVarSetUpGuideline.md
  .github/EnvVarSetUpGuideline.md
Labels: 🚨 change suggested

#131 Created Whole feedback page with multiple features
  frontend/package-lock.json
  frontend/package.json
  frontend/src/data/footerData.jsx
  frontend/src/pages/Feedback.jsx
  frontend/src/routes/RouterRoutes.jsx
Labels: 🚨 change suggested

#129 fix: responsiveness of header
  frontend/src/components/common/Header.jsx
Labels: 🚨 change suggested

#141 Add route for FeedBack
  backend/app.py
Labels: KWOC

#150 Converted styling of Failed.jsx
  frontend/src/pages/Failed.jsx
Labels: SWOC, Beginner

#149 Converted styling of Success.jsx
  frontend/src/pages/Success.jsx
  frontend/src/styles/pages/_success.scss
  frontend/src/styles/style.scss
Labels: SWOC, Beginner

#148 Converted styling of DisPred.jsx
  frontend/src/pages/DisPred.jsx
  frontend/src/styles/pages/_dispred.scss
  frontend/src/styles/style.scss
Labels: SWOC, Beginner

#147 Converted styling of MedicineSummary.jsx
  frontend/src/components/medicines/MedicineSummary.jsx
  frontend/src/hooks/useActive.js
  frontend/src/styles/pages/_medicinedetails.scss
  frontend/src/styles/style.scss
Labels: SWOC, Intermediate

#159 Converted styling of DiseasePrediction.jsx
  frontend/src/components/diseasePrediction/Home.jsx
  frontend/src/pages/DiseasePrediction.jsx
Labels: SWOC, Intermediate

#158 Converted styling of MyWallet.jsx
  frontend/src/pages/MyWallet.jsx
  frontend/src/styles/pages/_mywallet.scss
  frontend/src/styles/style.scss
Labels: SWOC, Intermediate

#165 Change the UI in acccordance with the dataset
  backend/app.py
  backend/requirements.txt
  frontend/package-lock.json
  frontend/src/data/symptoms.js
  frontend/src/pages/DiseasePrediction.jsx
Labels: 🚨 change suggested, SWOC, Advance

#176 feat: migrated meet page to tailwind css
  frontend/src/pages/MeetPage.jsx
  frontend/src/styles/pages/_meetpage.scss
  frontend/src/styles/style.scss
Labels: SWOC, Advance

#201 feat: added protection to feedback route
  frontend/src/pages/Feedback.jsx
Labels: 🚨 change suggested

#214 fix: bug in feedback page
  frontend/src/pages/Feedback.jsx
Labels: 🚨 change suggested
